/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#012d1d',
        'primary-container': '#1b4332',
        'on-primary': '#ffffff',
        'on-primary-container': '#86af99',
        'secondary': '#43664d',
        'secondary-container': '#c2e9c9',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#486a51',
        'tertiary': '#29261f',
        'tertiary-container': '#3f3c34',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#aca69b',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
        'surface': '#fcf9f8',
        'on-surface': '#1c1b1b',
        'surface-variant': '#e5e2e1',
        'on-surface-variant': '#414844',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'outline': '#717973',
        'outline-variant': '#c1c8c2',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
    },
  },
  plugins: [],
};
