/**
 * Citation Validator — Anti-Hallucination Guardrail
 * 
 * CRITICAL SAFETY REQUIREMENT:
 * This module deterministically validates that all legal citations in drafted documents
 * strictly originate from the verified retrieved knowledge chunks.
 * 
 * Under no circumstances may an ungrounded or hallucinated citation reach the user.
 */

const CITATION_REGEX = /\[(RTI-SEC-[A-Za-z0-9_()-]+|CPA-SEC-[A-Za-z0-9_()-]+)\]/g;

/**
 * Validates drafted document text against the authorized list of retrieved citation keys.
 * 
 * @param {string} draftText - The raw draft text generated by the AI model.
 * @param {Array<{citation_key: string}>} retrievedChunks - The verified chunks supplied in prompt context.
 * @returns {{ isValid: boolean, verifiedCitations: string[], unverifiedCitations: string[], cleanText: string }}
 */
export function validateDocumentCitations(draftText, retrievedChunks = []) {
  if (!draftText) {
    return { isValid: true, verifiedCitations: [], unverifiedCitations: [], cleanText: '' };
  }

  const validKeys = new Set(retrievedChunks.map((c) => c.citation_key));
  const foundMatches = Array.from(draftText.matchAll(CITATION_REGEX)).map((m) => m[1]);

  const verifiedCitations = [];
  const unverifiedCitations = [];

  for (const key of foundMatches) {
    if (validKeys.has(key)) {
      if (!verifiedCitations.includes(key)) {
        verifiedCitations.push(key);
      }
    } else {
      if (!unverifiedCitations.includes(key)) {
        unverifiedCitations.push(key);
      }
    }
  }

  // If unverified hallucinated citations exist, sanitize or fail closed
  let cleanText = draftText;
  if (unverifiedCitations.length > 0) {
    console.warn(`[Anti-Hallucination Engine] Detected ${unverifiedCitations.length} unverified citations:`, unverifiedCitations);
    for (const badKey of unverifiedCitations) {
      // Strip hallucinated citation markers
      const regex = new RegExp(`\\[${badKey}\\]`, 'g');
      cleanText = cleanText.replace(regex, '');
    }
  }

  return {
    isValid: unverifiedCitations.length === 0,
    verifiedCitations,
    unverifiedCitations,
    cleanText,
  };
}
